server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Profect-4th-IRUM/config-repo
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: develop
          search-paths:
            - api-gateway
            - service-discovery
            - member-service
            - product-service
            - order-service
            - payment-service
            - ai-service

#    bus:
#      enabled: true
#      destination: "bus-topic"
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,health,info